#指明注册中心的位置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18011/eureka/
#当前项目部署的端口
server:
  port: 18015
#当前项目的名称
spring:
  application:
    name: custom-feign

feign:
  hystrix:
    enabled: true